#!/usr/bin/env node
//
// Build step: src/assets/mascot/mascot.*.svg  →  src/mascot-expressions.js
//
// The designer ships pristine SVGs (no class attrs). At runtime the mascot
// layer needs two CSS hooks on each sclera-and-pupil eye pair so random
// blinking can toggle a scaleY() on the pupils. We add those hooks here
// instead of forcing the designer's export to carry them — that way the
// designer's round-trip stays lossless.
//
// What the transform does, per SVG:
//   1. Strip the root <svg>'s width / height attrs. We size via the host
//      element in JS; keeping them would fight that.
//   2. Find every <g>...</g> that wraps a white-fill ellipse followed by a
//      #1a1410-fill ellipse (that's the authoritative eye-group pattern in
//      this mascot's paint). The first gets class="eye eye-l", the second
//      class="eye eye-r", and the #1a1410 ellipse inside each gets
//      class="pupil".
//   3. Collapse inter-tag whitespace so the emitted JS strings are compact.
//
// Output: src/mascot-expressions.js, a single ESM module exporting an
// `EXPRESSIONS` object keyed by expression name.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const svgDir = resolve(repoRoot, "src/assets/mascot");
const outPath = resolve(repoRoot, "src/mascot-expressions.js");

const EXPRESSIONS = ["happy", "thinking", "excited", "sleepy", "error", "celebrating"];

function stripRootDims(svg) {
  return svg.replace(
    /<svg\b([^>]*?)\s+width="[^"]*"\s+height="[^"]*"/,
    "<svg$1"
  );
}

// Eye-group detector. We look for a <g> (possibly with existing attrs) that
// directly contains, as its first two element children, an ellipse with
// fill="#fff" and then an ellipse with fill="#1a1410". Whitespace between
// them is allowed.
const EYE_GROUP_RE = new RegExp(
  '<g([^>]*)>' +
    '(\\s*<ellipse\\b[^>]*fill="#fff"[^>]*>\\s*</ellipse>\\s*)' +
    '(<ellipse\\b)([^>]*fill="#1a1410"[^>]*>\\s*</ellipse>)',
  "g"
);

function annotateEyes(svg) {
  let count = 0;
  const annotated = svg.replace(
    EYE_GROUP_RE,
    (_match, gAttrs, scleraEllipse, pupilOpen, pupilRest) => {
      count += 1;
      const side = count === 1 ? "eye-l" : "eye-r";
      // Preserve any pre-existing attrs the designer may have added on the
      // <g>; class gets merged if already present, otherwise inserted.
      const newG = gAttrs.includes('class="')
        ? gAttrs.replace(/class="([^"]*)"/, `class="$1 eye ${side}"`)
        : ` class="eye ${side}"${gAttrs}`;
      return `<g${newG}>${scleraEllipse}${pupilOpen} class="pupil"${pupilRest}`;
    }
  );
  return { svg: annotated, eyesFound: count };
}

function minify(svg) {
  // Collapse whitespace between tags. Don't touch whitespace inside <text>
  // or attribute values (we have no <text> in these files).
  let s = svg.replace(/>\s+</g, "><").replace(/\s{2,}/g, " ").trim();
  // Strip leading zero on decimals inside attribute values: opacity="0.15" → ".15"
  s = s.replace(/="0(\.[0-9]+)"/g, '="$1"');
  // Self-close empty element tags for shape elements. (Keep <g>...</g> alone;
  // those wrap children or are used for grouping.) Safe because ammonia /
  // the browser treat <ellipse .../> and <ellipse ...></ellipse> equivalently
  // for SVG.
  s = s.replace(
    /<(ellipse|circle|rect|path|line|polygon|polyline)\b([^>]*)><\/\1>/g,
    "<$1$2/>"
  );
  // Compress path data: drop whitespace between a command letter and its
  // first number, drop whitespace before a command letter, collapse
  // internal spaces. Designer's export uses `M 110 232 L 96 278`; this
  // produces `M110 232L96 278`. Pure byte-win, renders identically.
  s = s.replace(/\bd="([^"]+)"/g, (_m, data) => {
    const compact = data
      .replace(/\s+/g, " ")
      .replace(/\s*([MmLlHhVvCcSsQqTtAaZz])\s*/g, "$1")
      .replace(/([0-9])\s+([-0-9.])/g, "$1 $2")
      .trim();
    return `d="${compact}"`;
  });
  return s;
}

function processSvg(name) {
  const raw = readFileSync(resolve(svgDir, `mascot.${name}.svg`), "utf8");
  let svg = raw;
  svg = stripRootDims(svg);
  const { svg: hooked, eyesFound } = annotateEyes(svg);
  svg = minify(hooked);
  return { svg, eyesFound };
}

const parts = [];
parts.push(
  "// AUTO-GENERATED by scripts/build-mascot.mjs — DO NOT EDIT BY HAND.",
  "// Re-run `pnpm build:mascot` (or any `pnpm build` / `pnpm dev`) after",
  "// editing the source SVGs under src/assets/mascot/.",
  "",
  "export const EXPRESSIONS = {"
);

for (const name of EXPRESSIONS) {
  const { svg, eyesFound } = processSvg(name);
  // `sleepy` draws closed eyes as paths, so zero eye groups is expected
  // there; elsewhere we require the pair.
  const expectedEyes = name === "sleepy" ? 0 : 2;
  if (eyesFound !== expectedEyes) {
    throw new Error(
      `mascot.${name}.svg: expected ${expectedEyes} eye groups, annotated ${eyesFound}. ` +
        `The designer's paint may have changed; inspect the eye-group pattern in build-mascot.mjs.`
    );
  }
  // Escape backticks + ${ so the SVG can live in a template literal
  const literal = svg.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  parts.push(`  ${name}: \`${literal}\`,`);
}
parts.push("};", "");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, parts.join("\n"), "utf8");

const bytes = Buffer.byteLength(parts.join("\n"), "utf8");
console.log(
  `build-mascot: wrote ${EXPRESSIONS.length} expressions to ${outPath.replace(repoRoot + "/", "")} (${bytes} bytes)`
);
